// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uygajfsoeqysoabevewy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5Z2FqZnNvZXF5c29hYmV2ZXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMjM2MjAsImV4cCI6MjA1Mjc5OTYyMH0.NxsC21NhKTJN6kc3MK5rUrYyb_tSuaTGjuzp2N7Iasg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);